"""Build the Atana harmonisation crosswalk — canonical.domain_crosswalk.

Phase 3 (Part C) of the Atana Data LATAM expansion. This materialises, as a
real queryable Parquet table, the domain crosswalk that until now lived only as
per-country mapping tables inside the four methodology docs.

WHAT THIS IS
------------
A single reference table that maps every national cultural-statistics
classification in the corpus — Mexico's INEGI CSCM functional areas, Colombia's
DANE CSECC product cuadros, Argentina's SInCA CSC segments, Costa Rica's CSCCR
sectors — plus the two international classifications already in the corpus
(UNCTAD CER creative-goods / creative-services codes, IBGE NCM chapters) onto a
common spine: the 14 domains of the 2025 UNESCO Framework for Cultural
Statistics (FCS) — 7 cultural + 7 transversal.

It lets a cross-country query resolve through ONE table while keeping the
definitional gaps VISIBLE — the `mapping_confidence` and `notes` columns record
exactly where a map is exact, good, approximate, or has no equivalent. Nothing
is silently reconciled (the methodological-pluralism principle — cf. Atana
Note #03). Three gaps are flagged with ★ in `notes` — they are findings, not
noise: Mexican artesanías, digital-content straddle, advertising/architecture.

The crosswalk is NOT raw source data — it is a curated artifact, regenerated by
this script from the inline data below. It therefore lives in the `canonical`
schema / `curated/` folder, un-timestamped: it is a living reference table, not
a versioned analytical snapshot.

SOURCES OF THE MAPPINGS (authoritative — the inline data is transcribed from):
    docs/methodology/inegi_csc.md        §5   — 10 CSCM áreas generales
    docs/methodology/dane_csecc.md       §4   — 22 trade-bearing CSECC cuadros
    docs/methodology/sinca_csc.md        §5   — 2 SInCA CSC segments
    docs/methodology/cr_bccr_csc.md      §5   — 4 CSCCR sectors
    _atana_intel/phase3_schema_design.md §C.4 — table design + the FCS spine

Output:
    curated/domain_crosswalk.parquet     (+ .meta.json)

Idempotent: inline data → DuckDB COPY to Parquet (no pyarrow); byte-identical
reruns. MotherDuck push gated behind a token (env var or .motherduck_token
file). No file in raw/ is read, moved or modified.

Usage:
    python etl/canonical__build_domain_crosswalk.py
"""
import hashlib
import json
import os
from datetime import date
from pathlib import Path

import duckdb
import pandas as pd

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT = REPO_ROOT / "curated"
OUT.mkdir(parents=True, exist_ok=True)

COLUMNS = [
    "source_schema",        # 'fcs2025','inegi','dane','sinca','cr_bccr','unctad','ibge_comex'
    "source_system",        # human-readable classification name
    "source_code",          # the code within that classification
    "source_label",         # the label within that classification
    "fcs2025_domain",        # the common spine — an FCS 2025 domain (or a bundle / NULL)
    "fcs2025_domain_type",   # 'cultural' | 'transversal' (or a verbatim bundle / NULL)
    "unctad_cer",           # nearest UNCTAD CER / service code; NULL if no equivalent
    "ibge_ncm_chapter",     # nearest IBGE NCM chapter(s); NULL if not a traded good
    "mapping_confidence",   # 'exact' | 'good' | 'approximate' | 'no-equivalent'
    "notes",                # the definitional gap, stated explicitly
]

CONFIDENCE_VALUES = {"exact", "good", "approximate", "no-equivalent"}

# ── The 2025 UNESCO FCS spine — 7 cultural + 7 transversal domains ───────────
FCS_CULTURAL = [
    ("FCS-C1", "Cultural and natural heritage",
     "Museums, monuments, archaeological and protected natural sites; "
     "heritage as a cultural domain."),
    ("FCS-C2", "Performing arts",
     "Theatre, dance, opera, live music performance, circus."),
    ("FCS-C3", "Visual arts and crafts",
     "Painting, sculpture, photography and crafts; the FCS merges fine art "
     "and craft into a single domain."),
    ("FCS-C4", "Books and press",
     "Books, newspapers, magazines, news agencies, publishing, printing."),
    ("FCS-C5", "Audiovisual",
     "Film, television, radio, video, streaming and recorded content."),
    ("FCS-C6", "Design",
     "Graphic, industrial, interior and fashion design and advertising; "
     "architecture sits partly here."),
    ("FCS-C7", "Music",
     "Composition, recording, music publishing, instruments."),
]
FCS_TRANSVERSAL = [
    ("FCS-T1", "Education in culture",
     "Cultural education and training across the system."),
    ("FCS-T2", "Archives",
     "Libraries and archives."),
    ("FCS-T3", "Cultural and creative goods manufacturing",
     "Manufacture of cultural and creative goods; the natural home for "
     "creative-goods-trade aggregates."),
    ("FCS-T4", "ICT and digital infrastructure",
     "Digital platforms, telecoms and internet infrastructure supporting "
     "culture."),
    ("FCS-T5", "Intangible cultural heritage",
     "Living heritage — oral traditions, rituals, knowledge and practices."),
    ("FCS-T6", "Social participation",
     "Cultural participation and practices — introduced by the 2025 FCS "
     "praxeological lens."),
    ("FCS-T7", "Intellectual property",
     "Copyright, marks and patents arising from cultural production."),
]
FCS_DOMAIN_LABELS = {label for _, label, _ in FCS_CULTURAL + FCS_TRANSVERSAL}


def spine_rows() -> list[dict]:
    """The 14 FCS domains — the canonical harmonisation target (maps to self)."""
    rows = []
    for code, label, note in FCS_CULTURAL:
        rows.append(dict(zip(COLUMNS, (
            "fcs2025", "2025 UNESCO FCS domain", code, label,
            label, "cultural", None, None, "exact",
            f"Canonical spine domain (cultural). {note}"))))
    for code, label, note in FCS_TRANSVERSAL:
        rows.append(dict(zip(COLUMNS, (
            "fcs2025", "2025 UNESCO FCS domain", code, label,
            label, "transversal", None, None, "exact",
            f"Canonical spine domain (transversal). {note}"))))
    return rows


# ── Mexico — INEGI CSCM, 10 áreas generales (inegi_csc.md §5) ────────────────
INEGI = [
    (1,  "Artes visuales y plásticas", "Visual arts and crafts", "cultural",
     "CER040", "97", "approximate",
     "FCS merges visual arts and crafts into one domain; UNCTAD CER040 "
     "bundles music + performing + visual arts — no clean isolate."),
    (2,  "Artes escénicas y espectáculos", "Performing arts", "cultural",
     "CER040", None, "approximate",
     "Live performance is not a traded good (no NCM chapter); CER040 only "
     "partially overlaps. INEGI also counts sporting spectacles — wider "
     "than the FCS domain."),
    (3,  "Música y conciertos", "Music", "cultural",
     "CER040", "92", "approximate",
     "NCM 92 = musical instruments only; recorded music sits in UNCTAD "
     "CER060. CER040 again bundles three arts."),
    (4,  "Libros, impresiones y prensa", "Books and press", "cultural",
     "CER030", "49", "good",
     "Closest clean match across all three classifications."),
    (5,  "Medios audiovisuales", "Audiovisual", "cultural",
     "CER010 + CER060", "37", "good",
     "Spans two UNCTAD CER codes — audiovisual goods (CER010) and recorded "
     "media / video games (CER060)."),
    (6,  "Artesanías", "Visual arts and crafts", "cultural",
     "CER020", "46, 67, 69, 71", "approximate",
     "★ Largest definitional gap: Mexican crafts are 18.4% of cultural GDP "
     "yet mostly informal household production; UNCTAD CER020 sees only the "
     "traded-goods fraction. In inegi.csc_comercio Artesanías records NA — "
     "Mexico's cultural-trade total structurally excludes its biggest domain."),
    (7,  "Diseño y servicios creativos", "Design", "cultural",
     "CER020 + CER050", "94", "approximate",
     "★ INEGI bundles industrial/graphic design + architecture + advertising; "
     "FCS Design is narrower and UNCTAD splits CER050 Architecture out. Also "
     "touches the transversal Intellectual property domain."),
    (8,  "Patrimonio cultural y natural", "Cultural and natural heritage",
     "cultural", "CER070", None, "good",
     "Heritage services; not a traded good (no NCM chapter)."),
    (9,  "Formación y difusión cultural", "Education in culture", "transversal",
     None, None, "good",
     "A transversal FCS domain — no UNCTAD / NCM equivalent by design."),
    (10, "Contenidos digitales e internet", "ICT and digital infrastructure",
     "transversal", "CER060", None, "approximate",
     "★ Straddles a transversal domain (ICT) and cultural Audiovisual "
     "(streaming). INEGI's fastest-growing area — partly culture, partly "
     "pure ICT; where the boundary is drawn moves Mexico's cultural GDP."),
]


def inegi_rows() -> list[dict]:
    rows = []
    for code, label, dom, dtype, cer, ncm, conf, note in INEGI:
        rows.append(dict(zip(COLUMNS, (
            "inegi", "CSCM área general", str(code), label,
            dom, dtype, cer, ncm, conf, note))))
    return rows


# ── Colombia — DANE CSECC, 22 trade-bearing product cuadros (dane_csecc.md §4)
# Confidence is 'approximate' throughout per the methodology doc (CSECC product
# granularity is finer than the FCS domains); cuadro 10 has no FCS equivalent.
DANE = [
    (4,  "Producción y presentación de artes escénicas", "Performing arts",
     "cultural", "CER040", None,
     "Live performance — no traded-good equivalent."),
    (7,  "Bibliotecas y archivos", "Archives", "transversal", None, None,
     "Maps to the transversal Archives domain."),
    (8,  "Preservación y museos", "Cultural and natural heritage", "cultural",
     "CER070", None, "Heritage services."),
    (10, "Parques de atracciones", None, None, None, None,
     "Amusement parks — recreation; no clean FCS domain. Carried so the "
     "row is not silently dropped."),
    (11, "Educación cultural preescolar–media", "Education in culture",
     "transversal", None, None, "Transversal FCS domain."),
    (13, "Educación cultural para el trabajo", "Education in culture",
     "transversal", None, None, "Transversal FCS domain."),
    (15, "Edición de libros", "Books and press", "cultural", "CER030", "49",
     "DANE splits publishing into 4 product cuadros (15/16/17/20); all four "
     "collapse to the single FCS Books and press domain."),
    (16, "Diarios, revistas y publicaciones", "Books and press", "cultural",
     "CER030", "49", "Part of the 4-cuadro DANE publishing split."),
    (17, "Otros trabajos de edición", "Books and press", "cultural",
     "CER030", "49", "Part of the 4-cuadro DANE publishing split."),
    (20, "Impresión y reproducción", "Books and press", "cultural",
     "CER030", "49", "Part of the 4-cuadro DANE publishing split."),
    (21, "Producción de películas, video y TV", "Audiovisual", "cultural",
     "CER010 + CER060", "37",
     "DANE splits audiovisual into 7 cuadros (21–27); all map to the single "
     "FCS Audiovisual domain."),
    (22, "Postproducción de audiovisuales", "Audiovisual", "cultural",
     "CER010", "37", "Part of the 7-cuadro DANE audiovisual split."),
    (23, "Distribución de programas de TV y cine", "Audiovisual", "cultural",
     "CER060", None, "Part of the 7-cuadro DANE audiovisual split."),
    (24, "Proyección de películas", "Audiovisual", "cultural",
     "CER010", None, "Part of the 7-cuadro DANE audiovisual split."),
    (25, "Transmisión y programación de radio", "Audiovisual", "cultural",
     "CER060", None, "Part of the 7-cuadro DANE audiovisual split."),
    (26, "Transmisión y programación de TV", "Audiovisual", "cultural",
     "CER060", None, "Part of the 7-cuadro DANE audiovisual split."),
    (27, "Distribución de programas de pago", "Audiovisual", "cultural",
     "CER060", None, "Part of the 7-cuadro DANE audiovisual split."),
    (29, "Agencias de noticias", "Books and press", "cultural", None, None,
     "News agencies — a press service; no clean UNCTAD goods code."),
    (31, "Joyas y artículos conexos", "Visual arts and crafts", "cultural",
     "CER024", "71",
     "Jewellery — CER024 is a leaf of UNCTAD CER020 (crafts/design goods)."),
    (32, "Instrumentos musicales", "Music", "cultural", "CER040", "92",
     "Musical instruments."),
    (33, "Juegos y juguetes", "Design / CC goods manufacturing",
     "cultural / transversal", "CER025", "95",
     "★ Toys and games straddle FCS Design and the transversal Cultural and "
     "creative goods manufacturing domain — no 1:1 map. CER025 is a leaf of "
     "UNCTAD CER020."),
    (35, "Servicios publicitarios", "Design", "cultural", "CER050-adjacent",
     None,
     "★ Advertising — FCS routes advertising under Design; UNCTAD treats it "
     "as a service (SAMA), not a CER goods code."),
]


def dane_rows() -> list[dict]:
    rows = []
    for code, label, dom, dtype, cer, ncm, note in DANE:
        conf = "no-equivalent" if dom is None else "approximate"
        rows.append(dict(zip(COLUMNS, (
            "dane", "CSECC product cuadro", str(code), label,
            dom, dtype, cer, ncm, conf, note))))
    return rows


# ── Argentina — SInCA CSC, 2 segments (sinca_csc.md §5) ──────────────────────
# The Argentine trade module is segment-level only — no product/sector detail —
# so a fine FCS crosswalk is not possible; the mapping is necessarily coarse.
SINCA = [
    ("bienes_culturales",
     "Bienes culturales (libros, discos, obras de arte, películas)",
     "Multiple — not separable", None, "CER000", None,
     "Argentina's CSC trade module is segment-level only. Cultural goods "
     "span FCS Books and press, Audiovisual, Visual arts and crafts and "
     "Music — not separable in this dataset. Maps to the UNCTAD "
     "all-creative-goods aggregate CER000."),
    ("servicios_culturales", "Servicios culturales",
     "Multiple — not separable", None, "SCRE", None,
     "Segment-level only. Cultural services span Audiovisual (cultural) and "
     "Information / ICT (transversal) — they cross both FCS domain types. "
     "Maps to the UNCTAD all-creative-services aggregate SCRE."),
]


def sinca_rows() -> list[dict]:
    rows = []
    for code, label, dom, dtype, cer, ncm, note in SINCA:
        rows.append(dict(zip(COLUMNS, (
            "sinca", "SInCA CSC segment", code, label,
            dom, dtype, cer, ncm, "approximate", note))))
    return rows


# ── Costa Rica — CSCCR, 4 sectors (cr_bccr_csc.md §5) ────────────────────────
CR_BCCR = [
    ("Editorial", "Editorial", "Books and press", "cultural", "CER030", "49",
     "good",
     "Clean match. From 2022 the CSCCR reports this sector only — see "
     "cr_bccr.csc_comercio.full_sector_coverage."),
    ("Audiovisual", "Audiovisual", "Audiovisual", "cultural",
     "CER010 + CER060", "37", "good",
     "Clean match; spans two UNCTAD CER codes."),
    ("Publicidad", "Publicidad", "Design", "cultural",
     "CER050-adjacent / SAMA", None, "approximate",
     "★ Advertising — FCS routes advertising under Design; UNCTAD treats it "
     "as a service (SAMA). The usual approximate case."),
    ("Música", "Música", "Music", "cultural", "CER040", "92", "good",
     "Clean match."),
]


def cr_bccr_rows() -> list[dict]:
    rows = []
    for code, label, dom, dtype, cer, ncm, conf, note in CR_BCCR:
        rows.append(dict(zip(COLUMNS, (
            "cr_bccr", "CSCCR sector", code, label,
            dom, dtype, cer, ncm, conf, note))))
    return rows


# ── UNCTAD CER — creative goods (8 codes: CER000 + CER010–CER070) ────────────
UNCTAD_GOODS = [
    ("CER000", "All creative goods", "Cultural and creative goods manufacturing",
     "transversal", "37, 46, 49, 92, 97", "good",
     "The all-creative-goods aggregate; maps to the transversal FCS "
     "goods-manufacturing domain. Sub-codes CER010–CER070 decompose it."),
    ("CER010", "Audiovisuals, multimedia and photography", "Audiovisual",
     "cultural", "37", "good", "Clean match to the cultural Audiovisual domain."),
    ("CER020", "Crafts and design goods", "Visual arts and crafts", "cultural",
     "46, 67, 69, 71, 94", "approximate",
     "Bundles crafts and design goods; the FCS splits crafts (Visual arts "
     "and crafts) from Design. Leaf codes CER021–CER027."),
    ("CER030", "Books and publishing", "Books and press", "cultural", "49",
     "good", "Clean match to the cultural Books and press domain."),
    ("CER040", "Music, performing and visual arts",
     "Music; Performing arts; Visual arts and crafts", "cultural", "92, 97",
     "approximate",
     "★ UNCTAD bundles three distinct FCS cultural domains into one goods "
     "code — no clean isolate. Any per-domain query through CER040 inherits "
     "this ambiguity."),
    ("CER050", "Architecture", "Design", "cultural", None, "approximate",
     "The FCS has no standalone Architecture domain; architecture sits "
     "partly under Design. UNCTAD also routes architecture via the SAMA "
     "service code."),
    ("CER060", "Software, video games and recorded media", "Audiovisual",
     "cultural", None, "approximate",
     "Recorded media and video games; also touches the transversal ICT and "
     "digital infrastructure domain."),
    ("CER070", "Cultural and natural heritage goods",
     "Cultural and natural heritage", "cultural", None, "good",
     "Heritage-related creative goods."),
]


def unctad_goods_rows() -> list[dict]:
    rows = []
    for code, label, dom, dtype, ncm, conf, note in UNCTAD_GOODS:
        rows.append(dict(zip(COLUMNS, (
            "unctad", "UNCTAD CER (creative goods)", code, label,
            dom, dtype, code, ncm, conf, note))))
    return rows


# ── UNCTAD — creative services (7 codes) ─────────────────────────────────────
UNCTAD_SERVICES = [
    ("SCRE", "All creative services", "Multiple — all creative services",
     None, "approximate",
     "The all-creative-services aggregate; spans audiovisual, ICT/software, "
     "advertising and heritage services — multiple FCS domains of both "
     "types. Sub-codes below decompose it."),
    ("SRND", "Research and development services", None, None, "no-equivalent",
     "R&D is inside UNCTAD's creative-services aggregate but has no FCS "
     "cultural domain — the FCS does not treat generic R&D as cultural. "
     "Carried for completeness."),
    ("SSFT", "Software services", "ICT and digital infrastructure",
     "transversal", "approximate",
     "Software services; the FCS routes these under the transversal ICT "
     "domain, with overlap into Design (digital and game design)."),
    ("SAUV", "Audiovisual services", "Audiovisual", "cultural", "good",
     "Clean match to the cultural Audiovisual domain."),
    ("SINF", "Information services", "ICT and digital infrastructure",
     "transversal", "approximate",
     "Information services; the closest FCS home is the transversal ICT "
     "domain."),
    ("SAMA", "Advertising, market research and architecture services",
     "Design", "cultural", "approximate",
     "Bundles advertising and architecture; FCS Design covers advertising "
     "and architecture partly — a many-to-one approximation."),
    ("SCRH", "Cultural, recreational and heritage services",
     "Cultural and natural heritage", "cultural", "approximate",
     "Covers heritage but also recreational and other personal/cultural "
     "services wider than the FCS heritage domain."),
]


def unctad_services_rows() -> list[dict]:
    rows = []
    for code, label, dom, dtype, conf, note in UNCTAD_SERVICES:
        rows.append(dict(zip(COLUMNS, (
            "unctad", "UNCTAD creative service", code, label,
            dom, dtype, code, None, conf, note))))
    return rows


# ── IBGE NCM — the 5 pure (100%) cultural chapters (manifest ibge_comex) ─────
IBGE_NCM = [
    ("37", "Photographic and cinematographic goods", "Audiovisual", "CER010",
     "One of the five 100%-cultural NCM chapters (is_pure_cultural in "
     "ibge_comex.tab_10_1)."),
    ("46", "Basketwork, wickerwork and plaiting-material manufactures",
     "Visual arts and crafts", "CER020",
     "Pure-cultural NCM chapter — crafts."),
    ("49", "Printed books, newspapers and pictures", "Books and press",
     "CER030", "Pure-cultural NCM chapter."),
    ("92", "Musical instruments", "Music", "CER040",
     "Pure-cultural NCM chapter — instruments only; recorded music is not in "
     "NCM 92."),
    ("97", "Works of art, collectors' pieces and antiques",
     "Visual arts and crafts", "CER040",
     "Pure-cultural NCM chapter. Antiques also touch Cultural and natural "
     "heritage — the chapter is assigned to its primary FCS domain."),
]


def ibge_ncm_rows() -> list[dict]:
    rows = []
    for code, label, dom, cer, note in IBGE_NCM:
        rows.append(dict(zip(COLUMNS, (
            "ibge_comex", "IBGE NCM chapter (pure-cultural)", code, label,
            dom, "cultural", cer, code, "good", note))))
    return rows


def build() -> pd.DataFrame:
    rows = (spine_rows() + inegi_rows() + dane_rows() + sinca_rows()
            + cr_bccr_rows() + unctad_goods_rows() + unctad_services_rows()
            + ibge_ncm_rows())
    return pd.DataFrame(rows, columns=COLUMNS)


def validate(df: pd.DataFrame) -> None:
    """Self-check the crosswalk before it is written."""
    print("Validating...")
    expect = {"fcs2025": 14, "inegi": 10, "dane": 22, "sinca": 2,
              "cr_bccr": 4, "unctad": 15, "ibge_comex": 5}
    got = df["source_schema"].value_counts().to_dict()
    for schema, n in expect.items():
        assert got.get(schema) == n, (
            f"{schema}: expected {n} rows, got {got.get(schema)}")
    assert len(df) == sum(expect.values()) == 72, f"total rows {len(df)} != 72"
    print(f"  ✓ 72 rows — " + ", ".join(f"{k} {v}" for k, v in expect.items()))

    bad = set(df["mapping_confidence"]) - CONFIDENCE_VALUES
    assert not bad, f"unexpected mapping_confidence values: {bad}"
    print(f"  ✓ mapping_confidence ∈ {sorted(CONFIDENCE_VALUES)}")

    # Every "clean" (single, non-bundle, non-null) fcs2025_domain must be one
    # of the 14 spine labels. Bundles (containing ';' or '/') and 'Multiple …'
    # rows and NULLs are the documented many-to-many / no-equivalent cases.
    clean_bad = []
    for d in df["fcs2025_domain"].dropna().unique():
        if ";" in d or "/" in d or d.startswith("Multiple"):
            continue
        if d not in FCS_DOMAIN_LABELS:
            clean_bad.append(d)
    assert not clean_bad, f"fcs2025_domain off-spine: {clean_bad}"
    print(f"  ✓ every clean fcs2025_domain is one of the 14 FCS spine domains")

    # No-equivalent rows must have a NULL domain; non-no-equivalent must not.
    ne = df["mapping_confidence"] == "no-equivalent"
    assert df.loc[ne, "fcs2025_domain"].isna().all(), \
        "a 'no-equivalent' row carries a domain"
    assert df.loc[~ne, "fcs2025_domain"].notna().all(), \
        "a non-'no-equivalent' row has a NULL domain"
    print(f"  ✓ NULL fcs2025_domain ⇔ mapping_confidence = 'no-equivalent' "
          f"({int(ne.sum())} rows)")

    # Coverage: which FCS spine domains are reached by at least one national
    # source row (inegi/dane/sinca/cr_bccr)?
    nat = df[df["source_schema"].isin(["inegi", "dane", "sinca", "cr_bccr"])]
    reached = set()
    for d in nat["fcs2025_domain"].dropna():
        for part in str(d).replace(";", "/").split("/"):
            p = part.strip()
            if p in FCS_DOMAIN_LABELS:
                reached.add(p)
    unreached = sorted(FCS_DOMAIN_LABELS - reached)
    print(f"  · {len(reached)}/14 FCS domains reached by a national CSC row; "
          f"not reached: {unreached or '—'}")
    conf = df["mapping_confidence"].value_counts().to_dict()
    print(f"  · confidence mix: " + ", ".join(
        f"{k} {conf.get(k, 0)}" for k in
        ["exact", "good", "approximate", "no-equivalent"]))


def write_parquet(df: pd.DataFrame) -> Path:
    out_path = OUT / "domain_crosswalk.parquet"
    con = duckdb.connect()
    con.register("df_data", df)
    con.execute(
        f"COPY df_data TO '{out_path}' (FORMAT PARQUET, COMPRESSION ZSTD)")
    size_kb = out_path.stat().st_size / 1024
    print(f"  ✓ {out_path.relative_to(REPO_ROOT)} — {len(df):,} rows, "
          f"{size_kb:.1f} KB")
    return out_path


def write_meta(out_path: Path, df: pd.DataFrame) -> None:
    derived_from = [
        "docs/methodology/inegi_csc.md",
        "docs/methodology/dane_csecc.md",
        "docs/methodology/sinca_csc.md",
        "docs/methodology/cr_bccr_csc.md",
        "_atana_intel/phase3_schema_design.md",
    ]
    composition = df["source_schema"].value_counts().to_dict()
    meta = {
        "table": "domain_crosswalk",
        "schema": "canonical",
        "description": "Atana harmonisation crosswalk — maps every national "
                       "cultural-statistics classification in the corpus "
                       "(INEGI CSCM, DANE CSECC, SInCA CSC, CSCCR) plus UNCTAD "
                       "CER and IBGE NCM onto the 14-domain 2025 UNESCO FCS "
                       "spine, with explicit mapping-confidence and gap notes.",
        "source": "Atana — curated artifact, not raw source data. The mappings "
                  "are transcribed from the four Phase 3 methodology docs and "
                  "the Phase 3 schema-design document.",
        "derived_from": derived_from,
        "build_script": "etl/canonical__build_domain_crosswalk.py",
        "build_date": str(date.today()),
        "grain": "one row per classification code (source_schema, source_code)",
        "row_composition": composition,
        "fcs_spine": "2025 UNESCO Framework for Cultural Statistics — "
                     "7 cultural + 7 transversal domains",
        "licence": "CC BY 4.0 (Atana) — the underlying classifications retain "
                   "their own licences",
        "notes": "Un-timestamped: this is a living reference table, "
                 "regenerated by the build script — not a versioned snapshot. "
                 "Bundle values in fcs2025_domain (containing ';' or '/', or "
                 "starting 'Multiple') and NULL domains are the documented "
                 "many-to-many / no-equivalent cases — never silently "
                 "reconciled.",
    }
    meta_path = out_path.with_suffix(".meta.json")
    meta_path.write_text(json.dumps(meta, indent=2, ensure_ascii=False))
    print(f"  ✓ {meta_path.relative_to(REPO_ROOT)}")


def maybe_push(df: pd.DataFrame, schema: str, table: str) -> None:
    """Push to MotherDuck if a valid token is available (MOTHERDUCK_TOKEN env
    var or a gitignored .motherduck_token file; must be a JWT). Off by default."""
    def _jwt(t) -> str:
        t = (t or "").strip()
        return t if (t.startswith("eyJ") and t.count(".") == 2) else ""
    token = _jwt(os.environ.get("MOTHERDUCK_TOKEN"))
    if not token:
        tf = REPO_ROOT / ".motherduck_token"
        token = _jwt(tf.read_text()) if tf.exists() else ""
    if not token:
        print(f"  · MotherDuck push skipped for atana.{schema}.{table} — no "
              f"valid token. Put a real MotherDuck token (a JWT: starts "
              f"'eyJ', two dots) in {REPO_ROOT}/.motherduck_token, then "
              f"re-run.")
        return
    con = duckdb.connect(f"md:atana?motherduck_token={token}")
    con.execute(f"CREATE SCHEMA IF NOT EXISTS atana.{schema}")
    con.register("df_data", df)
    con.execute(
        f"CREATE OR REPLACE TABLE atana.{schema}.{table} AS SELECT * FROM df_data")
    n = con.execute(f"SELECT COUNT(*) FROM atana.{schema}.{table}").fetchone()[0]
    print(f"  ✓ Synced atana.{schema}.{table} ({n:,} rows)")


def main() -> None:
    print("Building canonical.domain_crosswalk...")
    df = build()
    validate(df)
    out_path = write_parquet(df)
    write_meta(out_path, df)
    maybe_push(df, "canonical", "domain_crosswalk")
    print("Done.")


if __name__ == "__main__":
    main()
